services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app_ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
